version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: maven:3.5.0
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 3.5.0
      - run: mvn clean compile
      - run: mvn test
      - run: mvn deploy
